version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.7.5

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - ./dev.db:/tmp/dev.db

services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "{{cookiecutter.app_name}}-development"
    environment:
      DD_ENV: local
      DD_SERVICE: {{cookiecutter.app_name}}
      DD_VERSION: 1.0
      DD_LOGS_INJECTION: "true"
      LOG_LEVEL: info
      FLASK_ENV: development
    ports:
      - "5000:5000"
      - "2992:2992"
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "{{cookiecutter.app_name}}-production"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: pipenv run flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "{{cookiecutter.app_name}}-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

